import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

/**
 * Sends an email using Nodemailer
 * @param to Recipient email address
 * @param subject Subject of the email
 * @param text Plain text body of the email
 * @param html HTML body of the email
 * @returns Email sending status or error
 */
const sendEmail = async (
  to: string,
  subject: string,
  text: string,
  html: string
): Promise<string> => {
  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = process.env.SMTP_PORT;
  const emailUser = process.env.EMAIL_USERNAME;
  const emailPass = process.env.EMAIL_PASSWORD;


  

  if (!smtpHost || !smtpPort || !emailUser || !emailPass) {
    throw new Error(
      "SMTP configuration is missing. Please check your environment variables."
    );
  }

  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: parseInt(smtpPort, 10),
    auth: {
      user: emailUser,
      pass: emailPass,
    },
  });

  const mailOptions = {
    from: emailUser, // sender address
    to,
    subject,
    text,
    html,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log("Email sent: " + info.response);
    return `Email sent successfully to ${to}`;
  } catch (error) {
    console.error("Error sending email:", error);
    throw new Error("Failed to send email.");
  }
};

const sendEmailWithCC = async (
  to: string,
  cc: string[],
  subject: string,
  text: string,
  html: string
) => {
  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = process.env.SMTP_PORT;
  const emailUser = process.env.EMAIL_USERNAME;
  const emailPass = process.env.EMAIL_PASSWORD;

  if (!smtpHost || !smtpPort || !emailUser || !emailPass) {
    throw new Error("SMTP config missing.");
  }

  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: parseInt(smtpPort, 10),
    auth: {
      user: emailUser,
      pass: emailPass,
    },
  });

  const mailOptions = {
    from: emailUser,
    to,
    cc, // 🟢 CC added here
    subject,
    text,
    html,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log("Email sent:", info.response);
    return info;
  } catch (error) {
    console.log("Error sending CC email:", error);
    throw error;
  }
};


interface TicketEmailPayload {
  to: string;              // allowed_email selected by student
  subject: string;         // e.g. _0001
  studentName?: string;    // optional
  title: string;
  description: string;
  remarks?: string;
}



const sendTicketCreationEmail = async (data: TicketEmailPayload) => {
  try {
    const ccEnv = process.env.TICKET_CC_EMAILS || "";
    const ccList = ccEnv
      .split(",")
      .map((e) => e.trim())
      .filter((e) => e.length > 0);

    const fromName = process.env.TICKET_FROM_NAME || "Support Desk";

    const emailSubject = `New Ticket ${data.subject} - ${data.title}`;

    // HTML VERSION
    const html = `
      <div style="font-family: Arial, sans-serif; color: #333;">
        <h2>${fromName}</h2>
        <p><strong>Ticket ID:</strong> ${data.subject}</p>
        <p><strong>Title:</strong> ${data.title}</p>
        <p><strong>Description:</strong></p>
        <p>${data.description}</p>

        ${data.remarks
        ? `<p><strong>Remarks:</strong> ${data.remarks}</p>`
        : ""
      }

        ${data.studentName
        ? `<p><strong>Student:</strong> ${data.studentName}</p>`
        : ""
      }

        <hr style="border:0;border-top:1px solid #ccc;margin:20px 0;">
        <p>This email was auto-generated by the Student Support System.</p>
      </div>
    `;

    // TEXT VERSION
    const text = `
Ticket ID: ${data.subject}
Title: ${data.title}
Description: ${data.description}
${data.remarks ? `Remarks: ${data.remarks}` : ""}
${data.studentName ? `Student: ${data.studentName}` : ""}
    `;

    // 🔥 FIRE EMAIL — using your existing sendEmail() but with CC added
    await sendEmailWithCC(data.to, ccList, emailSubject, text, html);

    return true;
  } catch (err) {
    console.error("Error sending ticket creation email:", err);
    throw err;
  }
};
export { sendEmail, sendTicketCreationEmail };
